### ISSUE TITLE
How to define and customize code style?

### ISSUE THREAD

**Issue by sw-gong** [atom-community/atom-ide-code-format#13]
Hi,

It's not clear which style (yapf/autopep8?) is applied by default. Can you please clarify how one can define it?

Thanks!

**Comment by aminya** [comment]
It uses the default settings. You can add your config files if you want to modify them.

**Comment by sw-gong** [comment]
> It uses the default settings. You can add your config files if you want to modify them.

Thanks for your quick reply. Where can I find those "default settings"? How and where should I put config files?

**Comment by aminya** [comment]
You should refer to the actual formatter (like autopep). Each one has its own config file rules. So, check out their repositories.

**Comment by sw-gong** [comment]
I'm a bit confused. Which formatter (autoprep8 or yapf) is applied by default for *Code Format*? Or it only calls autopep? If that's the case, how to specify formatter as yapf?

**Comment by aminya** [comment]
Whatever set in your ide-python settings

**Comment by UziTech** [comment]
This package allows for other packages to format you code with a common interface. This package doesn't do any formatting itself.

This package essentially just makes it so every package doesn't make the user format code in different ways. You can use a single key stroke or command and this package will figure out which other package to use to format the code. If you don't have another package installed that actually does the formatting than the key stroke or command will do nothing.
